platform :ios, '6.0'
pod 'AFNetworking', '2.4.1'
pod 'Reachability', '>= 3.1.1'
pod 'SVProgressHUD', '>= 1.0'
pod 'FMDB', '>= 2.4'
pod 'NanoStore', '2.7.7'
pod 'AEFDataSource', '0.4.0'
pod 'XHRefreshControl', '3.6'